/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author a21pablosp
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAlumnos = new javax.swing.JDialog();
        lblAltaAlumno = new javax.swing.JLabel();
        btnLimpiarAlumno = new javax.swing.JButton();
        PanelAddAlumno = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblLocalidad = new javax.swing.JLabel();
        txtLocalidad = new javax.swing.JTextField();
        combModulos = new javax.swing.JComboBox<>();
        lblModulo = new javax.swing.JLabel();
        btnQuitarAlumno = new javax.swing.JButton();
        btnGrabarAlumno = new javax.swing.JButton();
        spMostrarModulos = new javax.swing.JScrollPane();
        lModulos = new javax.swing.JList<>();
        panelModulos = new javax.swing.JDialog();
        lblAltaModulo = new javax.swing.JLabel();
        btnGrabarModulos = new javax.swing.JButton();
        PanelAddModulos = new javax.swing.JPanel();
        lblNombreModulo = new javax.swing.JLabel();
        txtNombreAlumno = new javax.swing.JTextField();
        lblHorasModulo = new javax.swing.JLabel();
        txtHorasModulo = new javax.swing.JTextField();
        lblUnidadesModulo = new javax.swing.JLabel();
        txtUnidadesModulo = new javax.swing.JTextField();
        btnLimpiarModulos = new javax.swing.JButton();
        panelDataAlumno = new javax.swing.JDialog();
        lblBuscarAlumno = new javax.swing.JLabel();
        btnBuscarAlumno = new javax.swing.JButton();
        txtBuscarAlumno = new javax.swing.JTextField();
        PanelDALumnos = new javax.swing.JPanel();
        lblDatosNombre = new javax.swing.JLabel();
        lblDatosLocalidad = new javax.swing.JLabel();
        lblDatosHoras = new javax.swing.JLabel();
        txtDatosNombre = new javax.swing.JTextField();
        txtDatosLocalidas = new javax.swing.JTextField();
        txtDatosHoras = new javax.swing.JTextField();
        lblModulos = new javax.swing.JLabel();
        spLMod = new javax.swing.JScrollPane();
        LMod = new javax.swing.JList<>();
        jDialog1 = new javax.swing.JDialog();
        btnAnModulo = new javax.swing.JButton();
        btnAnAlumno = new javax.swing.JButton();
        btnVerAlumno = new javax.swing.JButton();
        BarraMenu = new javax.swing.JMenuBar();
        MenuAlumno = new javax.swing.JMenu();
        miAñadirAlumno = new javax.swing.JMenuItem();
        miVerAlumno = new javax.swing.JMenuItem();
        miGuardarAlumno = new javax.swing.JMenuItem();
        miSalvarAlumno = new javax.swing.JMenuItem();
        MenuModulo = new javax.swing.JMenu();
        miAddModulo = new javax.swing.JMenuItem();
        miGuardaModulo = new javax.swing.JMenuItem();
        miSalvarModulo = new javax.swing.JMenuItem();

        panelAlumnos.setMinimumSize(new java.awt.Dimension(500, 500));
        panelAlumnos.setModal(true);

        lblAltaAlumno.setText("ALTA ALUMNOS");

        btnLimpiarAlumno.setText("Limpiar");

        PanelAddAlumno.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Añadir Alumno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 255))); // NOI18N

        lblNombre.setText("Nombre:");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        lblLocalidad.setText("Localidad:");

        javax.swing.GroupLayout PanelAddAlumnoLayout = new javax.swing.GroupLayout(PanelAddAlumno);
        PanelAddAlumno.setLayout(PanelAddAlumnoLayout);
        PanelAddAlumnoLayout.setHorizontalGroup(
            PanelAddAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAddAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAddAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblLocalidad, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(PanelAddAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAddAlumnoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre))
                    .addGroup(PanelAddAlumnoLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(txtLocalidad, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelAddAlumnoLayout.setVerticalGroup(
            PanelAddAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAddAlumnoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(PanelAddAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelAddAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocalidad)
                    .addComponent(txtLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        lblModulo.setText("Módulos:");

        btnQuitarAlumno.setText("Quitar");

        btnGrabarAlumno.setText("Grabar");

        spMostrarModulos.setViewportView(lModulos);

        javax.swing.GroupLayout panelAlumnosLayout = new javax.swing.GroupLayout(panelAlumnos.getContentPane());
        panelAlumnos.getContentPane().setLayout(panelAlumnosLayout);
        panelAlumnosLayout.setHorizontalGroup(
            panelAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlumnosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAlumnosLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(panelAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblAltaAlumno)
                                .addComponent(PanelAddAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(spMostrarModulos, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelAlumnosLayout.createSequentialGroup()
                                    .addComponent(lblModulo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(combModulos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(42, 42, 42)
                        .addComponent(btnQuitarAlumno))
                    .addGroup(panelAlumnosLayout.createSequentialGroup()
                        .addComponent(btnGrabarAlumno)
                        .addGap(69, 69, 69)
                        .addComponent(btnLimpiarAlumno)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAlumnosLayout.setVerticalGroup(
            panelAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlumnosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblAltaAlumno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelAddAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combModulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnQuitarAlumno)
                    .addComponent(spMostrarModulos, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(panelAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiarAlumno)
                    .addComponent(btnGrabarAlumno))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelModulos.setMinimumSize(new java.awt.Dimension(400, 400));
        panelModulos.setModal(true);

        lblAltaModulo.setText("ALTA MÓDULOS");

        btnGrabarModulos.setText("Grabar");
        btnGrabarModulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarModulosActionPerformed(evt);
            }
        });

        PanelAddModulos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Añadir Módulo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 255))); // NOI18N

        lblNombreModulo.setText("Nombre:");

        txtNombreAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreAlumnoActionPerformed(evt);
            }
        });

        lblHorasModulo.setText("Horas:");

        lblUnidadesModulo.setText("Unidades:");

        txtUnidadesModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnidadesModuloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAddModulosLayout = new javax.swing.GroupLayout(PanelAddModulos);
        PanelAddModulos.setLayout(PanelAddModulosLayout);
        PanelAddModulosLayout.setHorizontalGroup(
            PanelAddModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAddModulosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAddModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAddModulosLayout.createSequentialGroup()
                        .addGroup(PanelAddModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreModulo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHorasModulo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelAddModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtHorasModulo, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(txtNombreAlumno))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelAddModulosLayout.createSequentialGroup()
                        .addComponent(lblUnidadesModulo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUnidadesModulo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 47, Short.MAX_VALUE))))
        );
        PanelAddModulosLayout.setVerticalGroup(
            PanelAddModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAddModulosLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(PanelAddModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreModulo)
                    .addComponent(txtNombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelAddModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtHorasModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHorasModulo))
                .addGap(18, 18, 18)
                .addGroup(PanelAddModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUnidadesModulo)
                    .addComponent(txtUnidadesModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnLimpiarModulos.setText("Limpiar");

        javax.swing.GroupLayout panelModulosLayout = new javax.swing.GroupLayout(panelModulos.getContentPane());
        panelModulos.getContentPane().setLayout(panelModulosLayout);
        panelModulosLayout.setHorizontalGroup(
            panelModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModulosLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panelModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAltaModulo)
                    .addComponent(PanelAddModulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelModulosLayout.createSequentialGroup()
                        .addComponent(btnGrabarModulos)
                        .addGap(88, 88, 88)
                        .addComponent(btnLimpiarModulos)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        panelModulosLayout.setVerticalGroup(
            panelModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModulosLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblAltaModulo)
                .addGap(18, 18, 18)
                .addComponent(PanelAddModulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGrabarModulos)
                    .addComponent(btnLimpiarModulos))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        panelDataAlumno.setMinimumSize(new java.awt.Dimension(500, 500));
        panelDataAlumno.setModal(true);

        lblBuscarAlumno.setText("Nombre a buscar: ");

        btnBuscarAlumno.setText("Buscar");

        PanelDALumnos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del alumno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 51, 255))); // NOI18N

        lblDatosNombre.setText("Nombre: ");

        lblDatosLocalidad.setText("Localidad:");

        lblDatosHoras.setText("Horas:");

        txtDatosNombre.setEditable(false);
        txtDatosNombre.setToolTipText("");
        txtDatosNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtDatosLocalidas.setEditable(false);

        txtDatosHoras.setEditable(false);
        txtDatosHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDatosHorasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDALumnosLayout = new javax.swing.GroupLayout(PanelDALumnos);
        PanelDALumnos.setLayout(PanelDALumnosLayout);
        PanelDALumnosLayout.setHorizontalGroup(
            PanelDALumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDALumnosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDALumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDatosLocalidad, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                    .addComponent(lblDatosNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDatosHoras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDALumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDatosNombre)
                    .addComponent(txtDatosLocalidas)
                    .addComponent(txtDatosHoras))
                .addContainerGap())
        );
        PanelDALumnosLayout.setVerticalGroup(
            PanelDALumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDALumnosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDALumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatosNombre)
                    .addComponent(txtDatosNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(PanelDALumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatosLocalidad)
                    .addComponent(txtDatosLocalidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(PanelDALumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatosHoras)
                    .addComponent(txtDatosHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        lblModulos.setText("Módulos:");

        spLMod.setViewportView(LMod);

        javax.swing.GroupLayout panelDataAlumnoLayout = new javax.swing.GroupLayout(panelDataAlumno.getContentPane());
        panelDataAlumno.getContentPane().setLayout(panelDataAlumnoLayout);
        panelDataAlumnoLayout.setHorizontalGroup(
            panelDataAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataAlumnoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelDataAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelDataAlumnoLayout.createSequentialGroup()
                        .addComponent(lblModulos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spLMod))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDataAlumnoLayout.createSequentialGroup()
                        .addComponent(lblBuscarAlumno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PanelDALumnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarAlumno)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panelDataAlumnoLayout.setVerticalGroup(
            panelDataAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataAlumnoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelDataAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscarAlumno)
                    .addComponent(btnBuscarAlumno)
                    .addComponent(txtBuscarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(PanelDALumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelDataAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDataAlumnoLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lblModulos))
                    .addGroup(panelDataAlumnoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spLMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAnModulo.setText("Añadir Módulo");
        btnAnModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnModuloActionPerformed(evt);
            }
        });

        btnAnAlumno.setText("Añadir Alumno");
        btnAnAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnAlumnoActionPerformed(evt);
            }
        });

        btnVerAlumno.setText("Ver Alumno");
        btnVerAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerAlumnoActionPerformed(evt);
            }
        });

        MenuAlumno.setText("Alumnos");

        miAñadirAlumno.setText("Añadir Alumno");
        miAñadirAlumno.setToolTipText("");
        MenuAlumno.add(miAñadirAlumno);

        miVerAlumno.setText("Ver Alumno");
        miVerAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVerAlumnoActionPerformed(evt);
            }
        });
        MenuAlumno.add(miVerAlumno);

        miGuardarAlumno.setText("Guarda Alumno");
        MenuAlumno.add(miGuardarAlumno);

        miSalvarAlumno.setText("Salvar Alumno");
        MenuAlumno.add(miSalvarAlumno);

        BarraMenu.add(MenuAlumno);

        MenuModulo.setText("Módulos");

        miAddModulo.setText("Añadir Módulo");
        MenuModulo.add(miAddModulo);

        miGuardaModulo.setText("Guardar Modulo");
        miGuardaModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGuardaModuloActionPerformed(evt);
            }
        });
        MenuModulo.add(miGuardaModulo);

        miSalvarModulo.setText("Salvar Modulo");
        MenuModulo.add(miSalvarModulo);

        BarraMenu.add(MenuModulo);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAnAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAnModulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVerAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(283, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btnAnAlumno)
                .addGap(30, 30, 30)
                .addComponent(btnAnModulo)
                .addGap(39, 39, 39)
                .addComponent(btnVerAlumno)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miVerAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVerAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miVerAlumnoActionPerformed

    private void miGuardaModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGuardaModuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miGuardaModuloActionPerformed

    private void btnAnModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnModuloActionPerformed
        panelModulos.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnModuloActionPerformed

    private void btnAnAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnAlumnoActionPerformed
        panelAlumnos.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnAlumnoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnGrabarModulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarModulosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrabarModulosActionPerformed

    private void txtNombreAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreAlumnoActionPerformed

    private void txtUnidadesModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnidadesModuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnidadesModuloActionPerformed

    private void txtDatosHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatosHorasActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_txtDatosHorasActionPerformed

    private void btnVerAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerAlumnoActionPerformed
        panelDataAlumno.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerAlumnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JList<String> LMod;
    private javax.swing.JMenu MenuAlumno;
    private javax.swing.JMenu MenuModulo;
    private javax.swing.JPanel PanelAddAlumno;
    private javax.swing.JPanel PanelAddModulos;
    private javax.swing.JPanel PanelDALumnos;
    private javax.swing.JButton btnAnAlumno;
    private javax.swing.JButton btnAnModulo;
    private javax.swing.JButton btnBuscarAlumno;
    private javax.swing.JButton btnGrabarAlumno;
    private javax.swing.JButton btnGrabarModulos;
    private javax.swing.JButton btnLimpiarAlumno;
    private javax.swing.JButton btnLimpiarModulos;
    private javax.swing.JButton btnQuitarAlumno;
    private javax.swing.JButton btnVerAlumno;
    private javax.swing.JComboBox<String> combModulos;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JList<String> lModulos;
    private javax.swing.JLabel lblAltaAlumno;
    private javax.swing.JLabel lblAltaModulo;
    private javax.swing.JLabel lblBuscarAlumno;
    private javax.swing.JLabel lblDatosHoras;
    private javax.swing.JLabel lblDatosLocalidad;
    private javax.swing.JLabel lblDatosNombre;
    private javax.swing.JLabel lblHorasModulo;
    private javax.swing.JLabel lblLocalidad;
    private javax.swing.JLabel lblModulo;
    private javax.swing.JLabel lblModulos;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreModulo;
    private javax.swing.JLabel lblUnidadesModulo;
    private javax.swing.JMenuItem miAddModulo;
    private javax.swing.JMenuItem miAñadirAlumno;
    private javax.swing.JMenuItem miGuardaModulo;
    private javax.swing.JMenuItem miGuardarAlumno;
    private javax.swing.JMenuItem miSalvarAlumno;
    private javax.swing.JMenuItem miSalvarModulo;
    private javax.swing.JMenuItem miVerAlumno;
    private javax.swing.JDialog panelAlumnos;
    private javax.swing.JDialog panelDataAlumno;
    private javax.swing.JDialog panelModulos;
    private javax.swing.JScrollPane spLMod;
    private javax.swing.JScrollPane spMostrarModulos;
    private javax.swing.JTextField txtBuscarAlumno;
    private javax.swing.JTextField txtDatosHoras;
    private javax.swing.JTextField txtDatosLocalidas;
    private javax.swing.JTextField txtDatosNombre;
    private javax.swing.JTextField txtHorasModulo;
    private javax.swing.JTextField txtLocalidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreAlumno;
    private javax.swing.JTextField txtUnidadesModulo;
    // End of variables declaration//GEN-END:variables
}
