/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package junio_r;

import java.util.Arrays;
import java.util.Date;
import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.UtilDateModel;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author a21pablosp
 */
public class JFrame extends javax.swing.JFrame {
    static final String JDBC_Driver = "com.mysql.cj.jdbc.Driver";
    static final String DB_URL = "jdbc:mysql://localhost/gamesteis";
    static final String Usuario = "root";
    static final String Password="root";

    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtgCategoria = new javax.swing.ButtonGroup();
        advertencia = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();
        tabClientes = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtFechaNacimiento = new javax.swing.JTextField();
        btnCalendar = new javax.swing.JButton();
        lblFecha = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        lblApellidos = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        rbtEmpresario = new javax.swing.JRadioButton();
        rbtParticular = new javax.swing.JRadioButton();
        cbHistorico = new javax.swing.JCheckBox();
        btnAlta = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnBaja = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProducto = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        codigoProducto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        spStockProducto = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        modificarProducto = new javax.swing.JButton();
        eliminarProducto = new javax.swing.JButton();
        precioProducto = new javax.swing.JTextField();
        nombreProducto = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaFactura = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaLineaVenta = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnCrearFactura = new javax.swing.JButton();
        codigoFactura = new javax.swing.JTextField();
        cbClientes = new javax.swing.JComboBox<>();
        fechaFactura = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        codigoFactura2 = new javax.swing.JTextField();
        codigoLineaVenta = new javax.swing.JTextField();
        cbProductos = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        spCantidadVenta = new javax.swing.JSpinner();
        jButton5 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        subTotal = new javax.swing.JTextField();
        iVA = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miLimpiar = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        advertencia.setMinimumSize(new java.awt.Dimension(300, 300));

        jLabel6.setText("ADVERTENCIA");

        jLabel7.setText("USTED TIENE CAMPOS SIN RELLENAR");

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout advertenciaLayout = new javax.swing.GroupLayout(advertencia.getContentPane());
        advertencia.getContentPane().setLayout(advertenciaLayout);
        advertenciaLayout.setHorizontalGroup(
            advertenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(advertenciaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, advertenciaLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(advertenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(advertenciaLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btnOK)))
                .addGap(49, 49, 49))
        );
        advertenciaLayout.setVerticalGroup(
            advertenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(advertenciaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6)
                .addGap(95, 95, 95)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(btnOK)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCodigo.setText("Codigo Cliente");

        txtCodigo.setEditable(false);
        txtCodigo.setMinimumSize(new java.awt.Dimension(64, 20));
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        lblNombre.setText("Nombre");

        lblDireccion.setText("Direccion");

        lblTelefono.setText("Telefono");

        lblEmail.setText("Email");

        txtFechaNacimiento.setMinimumSize(new java.awt.Dimension(64, 20));
        txtFechaNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaNacimientoActionPerformed(evt);
            }
        });

        btnCalendar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/junio_r/planner_application_calendar_3059.png"))); // NOI18N
        btnCalendar.setMaximumSize(new java.awt.Dimension(50, 50));
        btnCalendar.setMinimumSize(new java.awt.Dimension(50, 50));
        btnCalendar.setPreferredSize(new java.awt.Dimension(50, 50));
        btnCalendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalendarActionPerformed(evt);
            }
        });

        lblFecha.setText("Fecha Nacimiento");

        lblApellidos.setText("Apellidos");

        lblCategoria.setText("Categoria");

        rbtgCategoria.add(rbtEmpresario);
        rbtEmpresario.setText("Empresario");
        rbtEmpresario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtEmpresarioActionPerformed(evt);
            }
        });

        rbtgCategoria.add(rbtParticular);
        rbtParticular.setSelected(true);
        rbtParticular.setText("Particular");
        rbtParticular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtParticularActionPerformed(evt);
            }
        });

        cbHistorico.setText("Historico");
        cbHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHistoricoActionPerformed(evt);
            }
        });

        btnAlta.setText("Alta");
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");

        btnBaja.setText("Baja");
        btnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblCodigo)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCategoria)
                        .addGap(18, 18, 18)
                        .addComponent(rbtEmpresario)
                        .addGap(18, 18, 18)
                        .addComponent(rbtParticular)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnAlta)
                                .addGap(18, 18, 18)
                                .addComponent(btnModificar)
                                .addGap(18, 18, 18)
                                .addComponent(btnBaja))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTelefono)
                                .addGap(18, 18, 18)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbHistorico, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(107, 107, 107))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblApellidos)
                        .addGap(18, 18, 18)
                        .addComponent(txtApellidos)
                        .addGap(18, 18, 18)
                        .addComponent(lblFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtFechaNacimiento, txtNombre});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategoria)
                    .addComponent(rbtEmpresario)
                    .addComponent(rbtParticular))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblNombre)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblApellidos)
                                .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblFecha)
                                .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefono)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlta)
                    .addComponent(btnModificar)
                    .addComponent(btnBaja)
                    .addComponent(cbHistorico))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAlta, btnBaja, btnModificar, cbHistorico, lblApellidos, lblCategoria, lblCodigo, lblDireccion, lblEmail, lblFecha, lblNombre, lblTelefono, rbtEmpresario, rbtParticular, txtApellidos, txtCodigo, txtDireccion, txtEmail, txtFechaNacimiento, txtNombre, txtTelefono});

        txtCodigo.getAccessibleContext().setAccessibleName("");

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Categoria", "Nombre", "Direccion", "Telefono", "Email", "Fecha Baja"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblCliente.setShowGrid(true);
        tblCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCliente);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabClientes.addTab("Clientes", jPanel1);

        tblProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Producto", "Precio", "Stock"
            }
        ));
        tblProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblProducto);

        jLabel1.setText("Codigo Producto");

        jLabel2.setText("Precio");

        codigoProducto.setEditable(false);

        jLabel3.setText("Nombre");

        jLabel4.setText("Stock");

        jLabel5.setText("Unidades");

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarProducto(evt);
            }
        });

        modificarProducto.setText("Modificar");
        modificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarProductoActionPerformed(evt);
            }
        });

        eliminarProducto.setText("Eliminar");
        eliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarProductoActionPerformed(evt);
            }
        });

        precioProducto.setMaximumSize(new java.awt.Dimension(64, 22));
        precioProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioProductoActionPerformed(evt);
            }
        });

        nombreProducto.setMaximumSize(new java.awt.Dimension(250, 20));
        nombreProducto.setMinimumSize(new java.awt.Dimension(250, 20));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(precioProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(codigoProducto))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(spStockProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5))
                            .addComponent(nombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(modificarProducto)
                        .addGap(18, 18, 18)
                        .addComponent(eliminarProducto)
                        .addGap(133, 133, 133)))
                .addGap(130, 130, 130))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(nombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(spStockProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(precioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(modificarProducto)
                    .addComponent(eliminarProducto))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        tabClientes.addTab("Productos", jPanel4);

        tablaFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Factura", "Cliente", "Fecha"
            }
        ));
        tablaFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaFacturaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaFactura);

        tablaLineaVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Venta", "ID_Factura", "Nombre Producto", "Cantidad", "Precio"
            }
        ));
        jScrollPane4.setViewportView(tablaLineaVenta);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel8.setText("Codigo Factura");

        jLabel9.setText("Cliente");

        jLabel10.setText("Fecha");

        btnCrearFactura.setText("Crear");
        btnCrearFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearFacturaActionPerformed(evt);
            }
        });

        codigoFactura.setEditable(false);
        codigoFactura.setMaximumSize(new java.awt.Dimension(70, 20));
        codigoFactura.setMinimumSize(new java.awt.Dimension(70, 20));
        codigoFactura.setPreferredSize(new java.awt.Dimension(70, 24));

        cbClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        cbClientes.setMaximumSize(new java.awt.Dimension(150, 20));
        cbClientes.setMinimumSize(new java.awt.Dimension(150, 20));
        cbClientes.setPreferredSize(new java.awt.Dimension(100, 24));

        fechaFactura.setMaximumSize(new java.awt.Dimension(70, 20));
        fechaFactura.setMinimumSize(new java.awt.Dimension(70, 20));

        jLabel11.setText("Codigo Venta");

        jLabel12.setText("Codigo Factura");

        jLabel13.setText("Producto");

        codigoFactura2.setEditable(false);
        codigoFactura2.setMaximumSize(new java.awt.Dimension(70, 20));
        codigoFactura2.setMinimumSize(new java.awt.Dimension(70, 20));
        codigoFactura2.setPreferredSize(new java.awt.Dimension(70, 24));

        codigoLineaVenta.setEditable(false);
        codigoLineaVenta.setMaximumSize(new java.awt.Dimension(70, 20));
        codigoLineaVenta.setMinimumSize(new java.awt.Dimension(70, 20));
        codigoLineaVenta.setPreferredSize(new java.awt.Dimension(70, 24));

        cbProductos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        cbProductos.setMaximumSize(new java.awt.Dimension(100, 20));
        cbProductos.setMinimumSize(new java.awt.Dimension(100, 20));
        cbProductos.setPreferredSize(new java.awt.Dimension(100, 24));

        jLabel14.setText("Cantidad");

        spCantidadVenta.setPreferredSize(new java.awt.Dimension(70, 24));

        jButton5.setText("Agregar");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(btnCrearFactura)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(fechaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(cbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(codigoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(codigoLineaVenta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(codigoFactura2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(spCantidadVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(codigoLineaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(codigoFactura2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(cbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(spCantidadVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton5))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(codigoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(fechaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnCrearFactura)))
                .addGap(30, 38, Short.MAX_VALUE))
        );

        jLabel15.setText("SubTotal");

        jLabel16.setText("IVA");

        jLabel17.setText("TOTAL");

        subTotal.setMaximumSize(new java.awt.Dimension(70, 20));
        subTotal.setMinimumSize(new java.awt.Dimension(70, 20));
        subTotal.setPreferredSize(new java.awt.Dimension(70, 24));
        subTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subTotalActionPerformed(evt);
            }
        });

        iVA.setMaximumSize(new java.awt.Dimension(70, 20));
        iVA.setMinimumSize(new java.awt.Dimension(70, 20));
        iVA.setPreferredSize(new java.awt.Dimension(70, 24));

        total.setMaximumSize(new java.awt.Dimension(70, 20));
        total.setMinimumSize(new java.awt.Dimension(70, 20));
        total.setPreferredSize(new java.awt.Dimension(70, 24));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(18, 18, 18)
                                        .addComponent(subTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(46, 46, 46)
                                        .addComponent(iVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(29, 29, 29)
                                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(51, 51, 51))))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(subTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(iVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        tabClientes.addTab("Ventas", jPanel6);

        jMenu1.setText("File");

        miLimpiar.setText("Limpiar Texto");
        miLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLimpiarActionPerformed(evt);
            }
        });
        jMenu1.add(miLimpiar);

        jMenuItem1.setText("jMenuItem1");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(tabClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(tabClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
        // TODO add your handling code here:
       insertarClientes();
    }//GEN-LAST:event_btnAltaActionPerformed

    private void cargarTablaClientes(){
        try {
            String queryShow = null ;
            Connection conexion = DriverManager.getConnection(DB_URL, Usuario, Password);      
                queryShow = "SELECT id_cliente,categoria,nombre,direccion,"
                    + "telefono,email,fecha_baja from cliente";
            
            
            Statement st = conexion.createStatement();
            ResultSet rs = st.executeQuery(queryShow);
            while(rs.next()){
                String id = String.valueOf(rs.getInt("id_cliente"));
                String cat = rs.getString("categoria");
                String nombre = rs.getString("nombre");
                String direccion = rs.getString("direccion");
                String telefono = rs.getString("telefono");
                String email = rs.getString("email");
                String fecha_baja = rs.getString("fecha_baja");
                String tbData[]={id,cat,nombre,direccion,telefono,email,fecha_baja};
                DefaultTableModel tblModel= (DefaultTableModel)tblCliente.getModel();
                tblModel.addRow(tbData);
            }
        } catch (SQLException e){
            e.printStackTrace();
        }
    }
   private void insertarClientes() {
       if (txtNombre.getText().equalsIgnoreCase("")||txtApellidos.getText().equalsIgnoreCase("")||txtDireccion.getText().equalsIgnoreCase("")||txtFechaNacimiento.getText().equalsIgnoreCase("")||txtEmail.getText().equalsIgnoreCase("")) {
           advertencia.show();
       }else{
            try {
             String categoria = null;
             if (rbtEmpresario.isSelected()) {
                 categoria = "Empresario";
             } else if (rbtParticular.isSelected()) {
                 categoria = "Particular";
             }
             String clientes[] = {txtNombre.getText(), txtApellidos.getText(), txtDireccion.getText(),
                     txtFechaNacimiento.getText(), txtTelefono.getText(), txtEmail.getText(), categoria};
             Connection conexion = DriverManager.getConnection(DB_URL, Usuario, Password);

             String query = "INSERT INTO cliente (nombre, apellido, direccion, fecha_nacimiento, telefono, email, categoria) VALUES (?, ?, ?, ?, ?, ?, ?)";
             PreparedStatement sentencia = conexion.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
             sentencia.setString(1, txtNombre.getText());
             sentencia.setString(2, txtApellidos.getText());
             sentencia.setString(3, txtDireccion.getText());
             sentencia.setString(4, txtFechaNacimiento.getText());
             sentencia.setString(5, txtTelefono.getText());
             sentencia.setString(6, txtEmail.getText());
             sentencia.setString(7, categoria);
             int valor = sentencia.executeUpdate();

             if (valor > 0) {
                 ResultSet generatedKeys = sentencia.getGeneratedKeys();
                 if (generatedKeys.next()) {
                     String id = String.valueOf(generatedKeys.getLong(1));
                     String[] tbData = {id, categoria, txtNombre.getText(), txtDireccion.getText(),
                             txtTelefono.getText(), txtEmail.getText(), null};
                     DefaultTableModel tblModel = (DefaultTableModel) tblCliente.getModel();
                     tblModel.addRow(tbData);
                 }
             }
         } catch (SQLException e) {
             e.printStackTrace();
         }
       }
    
}

    private void rbtParticularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtParticularActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_rbtParticularActionPerformed

    private void btnCalendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalendarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalendarActionPerformed

    private void txtFechaNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaNacimientoActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void rbtEmpresarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtEmpresarioActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_rbtEmpresarioActionPerformed

    private void cbHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHistoricoActionPerformed
        // TODO add your handling code here:
        try {
            DefaultTableModel tblModel= (DefaultTableModel)tblCliente.getModel();
            tblModel.setRowCount(0);
            String queryShow = null ;
            Connection conexion = DriverManager.getConnection(DB_URL, Usuario, Password);
            if(cbHistorico.isSelected()){
            queryShow = "SELECT id_cliente,categoria,nombre,direccion,"
                    + "telefono,email,fecha_baja from cliente where fecha_baja is not null";
            }else{
            queryShow = "SELECT id_cliente,categoria,nombre,direccion,"
                    + "telefono,email,fecha_baja from cliente";  
            }
            
            
            Statement st = conexion.createStatement();
            ResultSet rs = st.executeQuery(queryShow);
            while(rs.next()){
                String id = String.valueOf(rs.getInt("id_cliente"));
                String cat = rs.getString("categoria");
                String nombre = rs.getString("nombre");
                String direccion = rs.getString("direccion");
                String telefono = rs.getString("telefono");
                String email = rs.getString("email");
                String fecha_baja = rs.getString("fecha_baja");
                String tbData[]={id,cat,nombre,direccion,telefono,email,fecha_baja};
                
                tblModel.addRow(tbData);
            }
        } catch (SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_cbHistoricoActionPerformed

    private void btnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCliente.getSelectedRow();
        if (selectedRow != -1) {
            try{
                String idCliente = tblCliente.getValueAt(selectedRow, 0).toString(); 
                SimpleDateFormat date = new SimpleDateFormat("dd-MM-yyyy");
                Date hoy = new Date();
                String fechaHoy = date.format(hoy);
                tblCliente.getModel().setValueAt(fechaHoy, selectedRow, tblCliente.getColumnCount() - 1);
                Connection conexion = DriverManager.getConnection(DB_URL, Usuario, Password);
                String query = "UPDATE cliente SET fecha_baja = ? WHERE id_cliente = ?";
                PreparedStatement ps = conexion.prepareStatement(query);
                ps.setString(1, fechaHoy);
                ps.setString(2, idCliente);
                int filas = ps.executeUpdate();
                if (filas >0){
                    System.out.println("Fino");
                }else{
                    System.out.println("Fallo");
                }
                ps.close();
                conexion.close();
            }catch(SQLException e){
                e.printStackTrace();
            }            
        }else {
        System.out.println("Seleccione un cliente para dar de baja.");
        }
    }//GEN-LAST:event_btnBajaActionPerformed

    private void tblClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClienteMouseClicked
        // TODO add your handling code here:
        int selectedRowIndex = tblCliente.getSelectedRow();
        if (selectedRowIndex != -1) {
            try {
                String selectedClientId = tblCliente.getValueAt(selectedRowIndex, 0).toString();
                
                Connection conexion = DriverManager.getConnection(DB_URL, Usuario, Password);
                String query = "SELECT * FROM cliente WHERE id_cliente = ?";
                PreparedStatement ps = conexion.prepareStatement(query);
                ps.setString(1, selectedClientId);
                ResultSet rs = ps.executeQuery();
                
                if (rs.next()) {
                    txtCodigo.setText(rs.getString("id_cliente"));
                    txtNombre.setText(rs.getString("nombre"));
                    txtApellidos.setText(rs.getString("apellido"));
                    txtDireccion.setText(rs.getString("direccion"));
                    txtFechaNacimiento.setText(rs.getString("fecha_nacimiento"));
                    txtTelefono.setText(rs.getString("telefono"));
                    txtEmail.setText(rs.getString("email"));                    
                    String categoria = rs.getString("categoria");
                    if ("Empresario".equals(categoria)) {
                        rbtEmpresario.setSelected(true);
                        rbtParticular.setSelected(false);
                    } else {
                        rbtEmpresario.setSelected(false);
                        rbtParticular.setSelected(true);
                    }
                }
                
                rs.close();
                ps.close();
                conexion.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }     
        }
    }//GEN-LAST:event_tblClienteMouseClicked

    private void miLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLimpiarActionPerformed
        // TODO add your handling code here:
         JTextField[] limpiar = {txtNombre, txtApellidos, txtCodigo, txtDireccion, txtEmail, txtFechaNacimiento, txtTelefono};
        for(int i = 0; i < limpiar.length; i++) {
            limpiar[i].setText("");
        limpiarProducto();
        limpiarFactura();
        }
        
        
    }//GEN-LAST:event_miLimpiarActionPerformed
    private void limpiarProducto(){
        JTextField[] limpiar = {codigoProducto,nombreProducto,precioProducto};
        for (int i = 0 ; i<limpiar.length;i++){
            limpiar[i].setText("");
        }
        spStockProducto.setValue(0);
    }
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        //TODO IMPLEMENTAR DOM y SAX
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void agregarProducto(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarProducto
        // TODO add your handling code here:
        insertProductos();
    }//GEN-LAST:event_agregarProducto

    private void precioProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioProductoActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        advertencia.hide();
    }//GEN-LAST:event_btnOKActionPerformed
    private void limpiarFactura(){
        JTextField[] limpiar = {codigoFactura , fechaFactura};
        for(int i = 0; i<limpiar.length;i++){
            limpiar[i].setText("");
        }
        cbClientes.setSelectedIndex(0);
        
    }
    private void btnCrearFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearFacturaActionPerformed
        // TODO add your handling code here:
        if(cbClientes.getSelectedItem().equals("") || fechaFactura.getText().equals("")){
            advertencia.show();
        }else{
            try{
                String idCliente = cbClientes.getSelectedItem().toString().split(". ")[0];
                
            String factura[] = {idCliente, fechaFactura.getText()};
             Connection conexion = DriverManager.getConnection(DB_URL, Usuario, Password);

             String query = "INSERT INTO facturas (idCliente, fecha) VALUES (?, ?)";
             PreparedStatement sentencia = conexion.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
             sentencia.setString(1, factura[0]);
             sentencia.setString(2, factura[1]);
             int valor = sentencia.executeUpdate();

             if (valor > 0) {
                 ResultSet generatedKeys = sentencia.getGeneratedKeys();
                 if (generatedKeys.next()) {
                     String id = String.valueOf(generatedKeys.getLong(1));
                     String[] tbData = {id, factura[0], factura[1], null};
                     DefaultTableModel tblModel = (DefaultTableModel) tablaFactura.getModel();
                     tblModel.addRow(tbData);
                 }
             }
         } catch (SQLException e) {
             e.printStackTrace();
         }
        }
    }//GEN-LAST:event_btnCrearFacturaActionPerformed

    private void subTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subTotalActionPerformed

    private void eliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarProductoActionPerformed
        // TODO add your handling code here:
        borrarProducto();
        limpiartabProducto();
        cargarTablaProducto();
    }//GEN-LAST:event_eliminarProductoActionPerformed

    private void tblProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductoMouseClicked
        // TODO add your handling code here:
        int selectedRowIndex = tblProducto.getSelectedRow();
        if (selectedRowIndex != -1) {
            try {
                String selectedProductoId = tblProducto.getValueAt(selectedRowIndex, 0).toString();
                
                Connection conexion = DriverManager.getConnection(DB_URL, Usuario, Password);
                String query = "SELECT * FROM producto WHERE id_producto = ?";
                PreparedStatement ps = conexion.prepareStatement(query);
                ps.setString(1, selectedProductoId);
                ResultSet rs = ps.executeQuery();
                
                if (rs.next()) {
                    codigoProducto.setText(rs.getString("id_producto"));
                    nombreProducto.setText(rs.getString("nombre"));
                    precioProducto.setText(rs.getString("precio"));
                    spStockProducto.setValue(rs.getInt("stock"));
                }
                
                rs.close();
                ps.close();
                conexion.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }     
        }
    }//GEN-LAST:event_tblProductoMouseClicked

    private void modificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarProductoActionPerformed

    private void tablaFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaFacturaMouseClicked
        // TODO add your handling code here:
        int selectedRowIndex = tablaFactura.getSelectedRow();
        if (selectedRowIndex != -1) {
            try {
                String selectedIdFactura = tablaFactura.getValueAt(selectedRowIndex, 0).toString();
                
                Connection conexion = DriverManager.getConnection(DB_URL, Usuario, Password);
                String query = "SELECT * FROM facturas WHERE id_factura = ?";
                PreparedStatement ps = conexion.prepareStatement(query);
                ps.setString(1, selectedIdFactura);
                ResultSet rs = ps.executeQuery();
                
                if (rs.next()) {
                    codigoProducto.setText(rs.getString("id_producto"));
                    nombreProducto.setText(rs.getString("nombre"));
                    precioProducto.setText(rs.getString("precio"));
                    spStockProducto.setValue(rs.getInt("stock"));
                }
                
                rs.close();
                ps.close();
                conexion.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }     
        }
    }//GEN-LAST:event_tablaFacturaMouseClicked
    private void limpiartabProducto(){
        DefaultTableModel modelo=(DefaultTableModel) tblProducto.getModel();
        modelo.setRowCount(0);
    }
    private void borrarProducto() {
        if (codigoProducto.getText().isEmpty()) {
            advertencia.show();
        }else{
            try{
                Connection conexion = DriverManager.getConnection(DB_URL,Usuario,Password);
                String query="DELETE FROM producto WHERE id_producto = ?";
                PreparedStatement sentencia = conexion.prepareStatement(query);
                sentencia.setString(1, codigoProducto.getText());
                sentencia.execute();
                tblProducto.removeAll();
                
            }catch(SQLException e){
                e.printStackTrace(); 
            }
        }
        
    }
    private void insertProductos(){
        if (nombreProducto.getText().equalsIgnoreCase("")||precioProducto.getText().equalsIgnoreCase("")||String.valueOf(spStockProducto.getValue()).equalsIgnoreCase("")) {
            advertencia.show();
        
        }else{
            try{
            
                Connection conexion = DriverManager.getConnection(DB_URL, Usuario, Password);

                String query = "INSERT INTO producto (nombre, precio, stock) VALUES (?, ?, ?)";
                PreparedStatement sentencia = conexion.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
                sentencia.setString(1, nombreProducto.getText());
                sentencia.setString(2, precioProducto.getText());
                sentencia.setString(3, String.valueOf(spStockProducto.getValue()));
                int valor = sentencia.executeUpdate();

                if (valor > 0) {
                    ResultSet generatedKeys = sentencia.getGeneratedKeys();
                    if (generatedKeys.next()) {
                        String id = String.valueOf(generatedKeys.getLong(1));
                        String[] tbData = {id, nombreProducto.getText(), precioProducto.getText(),String.valueOf(spStockProducto.getValue())};
                        DefaultTableModel tblModel = (DefaultTableModel) tblProducto.getModel();
                        tblModel.addRow(tbData);
                    }
                }
            }catch(SQLException e){
                e.printStackTrace();
            }
            limpiarProducto();
        }
        
    }
    private void cargarComboboxProductos(){
        try{
            
            String queryShow = null ;
            Connection conexion = DriverManager.getConnection(DB_URL, Usuario, Password);      
            queryShow = "SELECT id_producto, nombre FROM producto ORDER BY id_producto";
            
            Statement st = conexion.createStatement();
            ResultSet rs = st.executeQuery(queryShow);
            while (rs.next()) {
                cbProductos.addItem(rs.getInt("id_producto")+". "+rs.getString("nombre"));
                
            }
                
        }catch(SQLException e){
            e.printStackTrace();
        }
    }
    private void cargarComboboxClientes(){
        try{
            
            String queryShow = null ;
            Connection conexion = DriverManager.getConnection(DB_URL, Usuario, Password);      
            queryShow = "SELECT id_cliente, nombre FROM cliente ORDER BY id_cliente";
            
            Statement st = conexion.createStatement();
            ResultSet rs = st.executeQuery(queryShow);
            while (rs.next()) {
                cbClientes.addItem(rs.getInt("id_cliente")+". "+rs.getString("nombre"));
                
            }
                
        }catch(SQLException e){
            e.printStackTrace();
        }
    }
    private void cargarTablaProducto(){
        try {
            String queryShow = null ;
            Connection conexion = DriverManager.getConnection(DB_URL, Usuario, Password);      
                queryShow = "SELECT id_producto,nombre,precio,"
                    + "stock from producto";
            
            
            Statement st = conexion.createStatement();
            ResultSet rs = st.executeQuery(queryShow);
            while(rs.next()){
                String id = String.valueOf(rs.getInt("id_producto"));
                String nombre = rs.getString("nombre");
                String precio = rs.getString("precio");
                String stock = rs.getString("stock");
                String tbData[]={id,nombre,precio,stock};
                DefaultTableModel tblModel= (DefaultTableModel)tblProducto.getModel();
                tblModel.addRow(tbData);
            }
        } catch (SQLException e){
            e.printStackTrace();
        }
    }
    private void cargarTablaFacturas(){
        try {
            String queryShow = null ;
            Connection conexion = DriverManager.getConnection(DB_URL, Usuario, Password);      
                queryShow = "SELECT idFactura, idCliente, fecha FROM facturas";
            
            
            Statement st = conexion.createStatement();
            ResultSet rs = st.executeQuery(queryShow);
            while(rs.next()){
                String id = String.valueOf(rs.getInt("idFactura"));
                String cliente = rs.getString("idCliente");
                String fecha = rs.getString("fecha");
                String tbData[]={id,cliente,fecha};
                DefaultTableModel tblModel= (DefaultTableModel)tablaFactura.getModel();
                tblModel.addRow(tbData);
            }
        } catch (SQLException e){
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame jFrame = new JFrame();
                jFrame.setVisible(true);
                jFrame.cargarTablaClientes();
                jFrame.cargarTablaProducto();
                jFrame.cargarTablaFacturas();
                jFrame.cargarComboboxClientes();
                jFrame.cargarComboboxProductos();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog advertencia;
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnCalendar;
    private javax.swing.JButton btnCrearFactura;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnOK;
    private javax.swing.JComboBox<String> cbClientes;
    private javax.swing.JCheckBox cbHistorico;
    private javax.swing.JComboBox<String> cbProductos;
    private javax.swing.JTextField codigoFactura;
    private javax.swing.JTextField codigoFactura2;
    private javax.swing.JTextField codigoLineaVenta;
    private javax.swing.JTextField codigoProducto;
    private javax.swing.JButton eliminarProducto;
    private javax.swing.JTextField fechaFactura;
    private javax.swing.JTextField iVA;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JMenuItem miLimpiar;
    private javax.swing.JButton modificarProducto;
    private javax.swing.JTextField nombreProducto;
    private javax.swing.JTextField precioProducto;
    private javax.swing.JRadioButton rbtEmpresario;
    private javax.swing.JRadioButton rbtParticular;
    private javax.swing.ButtonGroup rbtgCategoria;
    private javax.swing.JSpinner spCantidadVenta;
    private javax.swing.JSpinner spStockProducto;
    private javax.swing.JTextField subTotal;
    private javax.swing.JTabbedPane tabClientes;
    private javax.swing.JTable tablaFactura;
    private javax.swing.JTable tablaLineaVenta;
    private javax.swing.JTable tblCliente;
    private javax.swing.JTable tblProducto;
    private javax.swing.JTextField total;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    
}
