/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package junio_r;

import java.util.Arrays;
import java.util.Date;
import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.UtilDateModel;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author a21pablosp
 */
public class JFrame extends javax.swing.JFrame {
    static final String JDBC_Driver = "com.mysql.cj.jdbc.Driver";
    static final String DB_URL = "jdbc:mysql://localhost/gamesteis";
    static final String Usuario = "root";
    static final String Password="root";

    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtgCategoria = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        tabClientes = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtFechaNacimiento = new javax.swing.JTextField();
        btnCalendar = new javax.swing.JButton();
        lblFecha = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        lblApellidos = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        rbtEmpresario = new javax.swing.JRadioButton();
        rbtParticular = new javax.swing.JRadioButton();
        cbHistorico = new javax.swing.JCheckBox();
        btnAlta = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnBaja = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miLimpiar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCodigo.setText("Codigo Cliente");

        txtCodigo.setEditable(false);
        txtCodigo.setMinimumSize(new java.awt.Dimension(64, 20));
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        lblNombre.setText("Nombre");

        lblDireccion.setText("Direccion");

        lblTelefono.setText("Telefono");

        lblEmail.setText("Email");

        txtFechaNacimiento.setMinimumSize(new java.awt.Dimension(64, 20));
        txtFechaNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaNacimientoActionPerformed(evt);
            }
        });

        btnCalendar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/junio_r/planner_application_calendar_3059.png"))); // NOI18N
        btnCalendar.setMaximumSize(new java.awt.Dimension(50, 50));
        btnCalendar.setMinimumSize(new java.awt.Dimension(50, 50));
        btnCalendar.setPreferredSize(new java.awt.Dimension(50, 50));
        btnCalendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalendarActionPerformed(evt);
            }
        });

        lblFecha.setText("Fecha Nacimiento");

        lblApellidos.setText("Apellidos");

        lblCategoria.setText("Categoria");

        rbtgCategoria.add(rbtEmpresario);
        rbtEmpresario.setText("Empresario");
        rbtEmpresario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtEmpresarioActionPerformed(evt);
            }
        });

        rbtgCategoria.add(rbtParticular);
        rbtParticular.setSelected(true);
        rbtParticular.setText("Particular");
        rbtParticular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtParticularActionPerformed(evt);
            }
        });

        cbHistorico.setText("Historico");
        cbHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHistoricoActionPerformed(evt);
            }
        });

        btnAlta.setText("Alta");
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");

        btnBaja.setText("Baja");
        btnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblCodigo)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCategoria)
                        .addGap(18, 18, 18)
                        .addComponent(rbtEmpresario)
                        .addGap(18, 18, 18)
                        .addComponent(rbtParticular)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnAlta)
                                .addGap(18, 18, 18)
                                .addComponent(btnModificar)
                                .addGap(18, 18, 18)
                                .addComponent(btnBaja))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTelefono)
                                .addGap(18, 18, 18)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbHistorico, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(107, 107, 107))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblApellidos)
                        .addGap(18, 18, 18)
                        .addComponent(txtApellidos)
                        .addGap(18, 18, 18)
                        .addComponent(lblFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtFechaNacimiento, txtNombre});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategoria)
                    .addComponent(rbtEmpresario)
                    .addComponent(rbtParticular))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblNombre)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblApellidos)
                                .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblFecha)
                                .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefono)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlta)
                    .addComponent(btnModificar)
                    .addComponent(btnBaja)
                    .addComponent(cbHistorico))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAlta, btnBaja, btnModificar, cbHistorico, lblApellidos, lblCategoria, lblCodigo, lblDireccion, lblEmail, lblFecha, lblNombre, lblTelefono, rbtEmpresario, rbtParticular, txtApellidos, txtCodigo, txtDireccion, txtEmail, txtFechaNacimiento, txtNombre, txtTelefono});

        txtCodigo.getAccessibleContext().setAccessibleName("");

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Categoria", "Nombre", "Direccion", "Telefono", "Email", "Fecha Baja"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblCliente.setShowGrid(true);
        tblCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCliente);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabClientes.addTab("Clientes", jPanel1);

        jMenu1.setText("File");

        miLimpiar.setText("Limpiar Texto");
        miLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLimpiarActionPerformed(evt);
            }
        });
        jMenu1.add(miLimpiar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(tabClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(tabClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
        // TODO add your handling code here:
       insertarClientes();
    }//GEN-LAST:event_btnAltaActionPerformed

    private void cargarTablaClientes(){
        try {
            String queryShow = null ;
            Connection conexion = DriverManager.getConnection(DB_URL, Usuario, Password);      
                queryShow = "SELECT id_cliente,categoria,nombre,direccion,"
                    + "telefono,email,fecha_baja from cliente";
            
            
            Statement st = conexion.createStatement();
            ResultSet rs = st.executeQuery(queryShow);
            while(rs.next()){
                //data will be added until finish
                String id = String.valueOf(rs.getInt("id_cliente"));
                String cat = rs.getString("categoria");
                String nombre = rs.getString("nombre");
                String direccion = rs.getString("direccion");
                String telefono = rs.getString("telefono");
                String email = rs.getString("email");
                String fecha_baja = rs.getString("fecha_baja");
                // string array for stroe data into jtable
                String tbData[]={id,cat,nombre,direccion,telefono,email,fecha_baja};
                DefaultTableModel tblModel= (DefaultTableModel)tblCliente.getModel();
                //add string array data into jtable
                tblModel.addRow(tbData);
            }
        } catch (SQLException e){
            e.printStackTrace();
        }
    }
   private void insertarClientes() {
    try {
        String categoria = null;
        if (rbtEmpresario.isSelected()) {
            categoria = "Empresario";
        } else if (rbtParticular.isSelected()) {
            categoria = "Particular";
        }
        String clientes[] = {txtNombre.getText(), txtApellidos.getText(), txtDireccion.getText(),
                txtFechaNacimiento.getText(), txtTelefono.getText(), txtEmail.getText(), categoria};
        Connection conexion = DriverManager.getConnection(DB_URL, Usuario, Password);

        String query = "INSERT INTO cliente (nombre, apellido, direccion, fecha_nacimiento, telefono, email, categoria) VALUES (?, ?, ?, ?, ?, ?, ?)";
        PreparedStatement sentencia = conexion.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
        sentencia.setString(1, txtNombre.getText());
        sentencia.setString(2, txtApellidos.getText());
        sentencia.setString(3, txtDireccion.getText());
        sentencia.setString(4, txtFechaNacimiento.getText());
        sentencia.setString(5, txtTelefono.getText());
        sentencia.setString(6, txtEmail.getText());
        sentencia.setString(7, categoria);
        int valor = sentencia.executeUpdate();
        
        if (valor > 0) {
            // If the insertion was successful, add the new client to the table
            ResultSet generatedKeys = sentencia.getGeneratedKeys();
            if (generatedKeys.next()) {
                String id = String.valueOf(generatedKeys.getLong(1));
                String[] tbData = {id, categoria, txtNombre.getText(), txtDireccion.getText(),
                        txtTelefono.getText(), txtEmail.getText(), null};
                DefaultTableModel tblModel = (DefaultTableModel) tblCliente.getModel();
                tblModel.addRow(tbData);
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
}

    private void rbtParticularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtParticularActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_rbtParticularActionPerformed

    private void btnCalendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalendarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalendarActionPerformed

    private void txtFechaNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaNacimientoActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void rbtEmpresarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtEmpresarioActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_rbtEmpresarioActionPerformed

    private void cbHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHistoricoActionPerformed
        // TODO add your handling code here:
        try {
            DefaultTableModel tblModel= (DefaultTableModel)tblCliente.getModel();
            tblModel.setRowCount(0);
            String queryShow = null ;
            Connection conexion = DriverManager.getConnection(DB_URL, Usuario, Password);
            if(cbHistorico.isSelected()){
            queryShow = "SELECT id_cliente,categoria,nombre,direccion,"
                    + "telefono,email,fecha_baja from cliente where fecha_baja is not null";
            }else{
            queryShow = "SELECT id_cliente,categoria,nombre,direccion,"
                    + "telefono,email,fecha_baja from cliente";  
            }
            
            
            Statement st = conexion.createStatement();
            ResultSet rs = st.executeQuery(queryShow);
            while(rs.next()){
                //data will be added until finish
                String id = String.valueOf(rs.getInt("id_cliente"));
                String cat = rs.getString("categoria");
                String nombre = rs.getString("nombre");
                String direccion = rs.getString("direccion");
                String telefono = rs.getString("telefono");
                String email = rs.getString("email");
                String fecha_baja = rs.getString("fecha_baja");
                // string array for stroe data into jtable
                String tbData[]={id,cat,nombre,direccion,telefono,email,fecha_baja};
                
                //add string array data into jtable
                tblModel.addRow(tbData);
            }
        } catch (SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_cbHistoricoActionPerformed

    private void btnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCliente.getSelectedRow();
        if (selectedRow != -1) {
            try{
                String idCliente = tblCliente.getValueAt(selectedRow, 0).toString(); 
                SimpleDateFormat date = new SimpleDateFormat("dd-MM-yyyy");
                Date hoy = new Date();
                String fechaHoy = date.format(hoy);
                tblCliente.getModel().setValueAt(fechaHoy, selectedRow, tblCliente.getColumnCount() - 1);
                Connection conexion = DriverManager.getConnection(DB_URL, Usuario, Password);
                String query = "UPDATE cliente SET fecha_baja = ? WHERE id_cliente = ?";
                PreparedStatement ps = conexion.prepareStatement(query);
                ps.setString(1, fechaHoy);
                ps.setString(2, idCliente);
                int filas = ps.executeUpdate();
                if (filas >0){
                    System.out.println("Fino");
                }else{
                    System.out.println("Fallo");
                }
                ps.close();
                conexion.close();
            }catch(SQLException e){
                e.printStackTrace();
            }            
        }else {
        System.out.println("Seleccione un cliente para dar de baja.");
    }
    }//GEN-LAST:event_btnBajaActionPerformed

    private void tblClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClienteMouseClicked
        // TODO add your handling code here:
        int selectedRowIndex = tblCliente.getSelectedRow();
        if (selectedRowIndex != -1) {
            try {
                String selectedClientId = tblCliente.getValueAt(selectedRowIndex, 0).toString(); // Assuming client ID is in the first column
                
                // Query the database to get client information
                Connection conexion = DriverManager.getConnection(DB_URL, Usuario, Password);
                String query = "SELECT * FROM cliente WHERE id_cliente = ?";
                PreparedStatement ps = conexion.prepareStatement(query);
                ps.setString(1, selectedClientId);
                ResultSet rs = ps.executeQuery();
                
                // If a result is found, populate the text fields with the retrieved data
                if (rs.next()) {
                    txtCodigo.setText(rs.getString("id_cliente"));
                    txtNombre.setText(rs.getString("nombre"));
                    txtApellidos.setText(rs.getString("apellido"));
                    txtDireccion.setText(rs.getString("direccion"));
                    txtFechaNacimiento.setText(rs.getString("fecha_nacimiento"));
                    txtTelefono.setText(rs.getString("telefono"));
                    txtEmail.setText(rs.getString("email"));                    
                    String categoria = rs.getString("categoria");
                    if ("Empresario".equals(categoria)) {
                        rbtEmpresario.setSelected(true);
                        rbtParticular.setSelected(false);
                    } else {
                        rbtEmpresario.setSelected(false);
                        rbtParticular.setSelected(true);
                    }
                }
                
                // Close resources
                rs.close();
                ps.close();
                conexion.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }     
        }
    }//GEN-LAST:event_tblClienteMouseClicked

    private void miLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLimpiarActionPerformed
        // TODO add your handling code here:
         JTextField[] limpiar = {txtNombre, txtApellidos, txtCodigo, txtDireccion, txtEmail, txtFechaNacimiento, txtTelefono};
        for(int i = 0; i < limpiar.length; i++) {
            limpiar[i].setText("");
        }
        
    }//GEN-LAST:event_miLimpiarActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame jFrame = new JFrame();
                jFrame.setVisible(true);
                jFrame.cargarTablaClientes();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnCalendar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JCheckBox cbHistorico;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JMenuItem miLimpiar;
    private javax.swing.JRadioButton rbtEmpresario;
    private javax.swing.JRadioButton rbtParticular;
    private javax.swing.ButtonGroup rbtgCategoria;
    private javax.swing.JTabbedPane tabClientes;
    private javax.swing.JTable tblCliente;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
